// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package groupcachefb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetRequest(buf []byte, offset flatbuffers.UOffsetT) *GetRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetRequest) Group() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GetRequest) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GetRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GetRequestAddGroup(builder *flatbuffers.Builder, group flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(group), 0)
}
func GetRequestAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func GetRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
